Dev
Valeriya266/sedona pull request #2
Opened 2024-10-13 11:16 UTC by Valeriya266

2024-10-18 17:07 UTC, Allegathor requested changes

2024-10-18 17:07 UTC, Allegathor commented on index.html
> +                <a href=""><img href="./images/find.svg" class="header__widgets_widget" alt="find"></a>
Разобраться с img, с файлами всё ок - проверял.
Наводка: проблема в атрибутах

2024-10-18 17:07 UTC, Allegathor commented on index.html
> +                <button class="header__btn">хочу сюда!</button>
У коричневых кнопок нет границ (бордера) - исправить через css

2024-10-18 17:07 UTC, Allegathor commented on style.css
>  body {
У боди не сделан сброс (reset), обнулить отступы
Вообще говоря, как вариант можно использовать такой сброс для всех элементов + установка box-sizing:
```css
*, ::before, ::after {
    box-sizing: border-box;
    margin: 0;
    padding: 0;
}
```
В дальнейшем лучше ознакомиться с различными практиками для css-reset

2024-10-18 17:07 UTC, Allegathor commented on style.css
>  body {
Появился горизонтальный скролл, см. скрин
![image](https://github.com/user-attachments/assets/f8fc4a2e-0953-4cf5-8396-200d7906f914)

2024-10-18 17:07 UTC, Allegathor commented on style.css
> +    line-height: 21px;
line-height лучше задавать в относительных единицах, как коэффициент

2024-10-18 17:07 UTC, Allegathor commented on style.css
> +div[class*=_container] {
Этооооо что такооооеее
Подход оригинальный, с хитрецой, потенциально коварный и опасный.
Лучше будет переверстать и сделать один класс-контейнер для основного содержимого, в котором будет всё. В данном случае надо будет разбить на два (header внутри с контейнером, изображение, затем основное содержимое, внутри которого контейнер) 

Либо оставить в таком же виде наименования классов, но правила сделать примерно так:
```css
.header__container, .main__container, footer__container {
  margin: 0 auto;
  padding: 0 15px;
  overflow: hidden;
  max-width: 1200;
}

.header__container {
/*св-ва конкретно для контейнера хэдера, если необходимо */
}

.main__container {
/*св-ва конкретно для контейнера основного содержимого, если необходимо */
}

.footer__container {
/*св-ва конкретно для контейнера основного содержимого, если необходимо*/
}
```

Ну и в main__container завернуть всё основное содержимое, а не отдельно на каждый блок этот контейнер использовать

2024-10-18 17:07 UTC, Allegathor commented on index.html
> +                <ul class="header__menu_menu-list">
Здесь что-то пошло не так. Почему header_container с одним подчеркиванием?
Почему header__menu_menu-list? Это как понимать?
У элемента только один родитель — это его блок. Соответственно, header__menu-list и внутри header__menu-list-item, не надо городить.

Как вариант - можно вынести этот ul в блок и будет menu-list, а его потомки будут menu-list__item

2024-10-18 17:07 UTC, Allegathor commented on index.html
> +            <div class="main-text__text">Рассмотрим 5 причин, по которым Седона круче, чем Гранд-Каньон!</div>
Почему это не тег параграф? 🤔

2024-10-18 17:07 UTC, Allegathor commented on index.html
> +        <div class="content_container">
Это элемент или блок с модификатором? Я так понимаю, что подразумевался элемент, тогда нижнее подчеркивание должно быть двойное

2024-10-18 17:36 UTC, Allegathor commented on index.html
> +                <h1 class="find-hotel__text_title">Заинтересовались?</h1>
Следует использовать только один заголовок первого уровня на странице:
![image](https://github.com/user-attachments/assets/cf452d42-4616-47a6-9353-67fde6768f79)

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements#avoid_using_multiple_h1_elements_on_one_page

В данном случае я бы сделал h1 вот этот текст — "Седона — небольшой городок в Аризоне, заслуживающий большего!". И его же использовал для title страницы. Да, получается странно, что он не самый большой по размеру, но такое часто бывает на практике. Бывают случаи, когда h1 вообще не отображают визуально, но оставляют и исползуют только для SEO.

2024-10-18 17:36 UTC, Allegathor commented on index.html
> +            <div class="footer__phonenumber">+7 (812) 812-12-12</div>
Телефон и email лучше всего оформлять как ссылки:

2024-10-18 17:44 UTC, Allegathor requested changes

2024-10-18 17:44 UTC, Allegathor commented on style.css
> +p + p {
От использования подобного рода селекторов лучше уходить, особенно такое в БЭМ не приветствуется: селекторы вложенных/дочерних элементов, селекторы соседних элементов c тегами. Ты можешь ведь для класса эти правила задать внутри карточек

2024-10-19 10:18 UTC, Valeriya266 commented on index.html
> +                <a href=""><img href="./images/find.svg" class="header__widgets_widget" alt="find"></a>
исправила на src, теперь ок

2024-10-19 10:23 UTC, Valeriya266 commented on index.html
> +                <button class="header__btn">хочу сюда!</button>
исправила

2024-10-19 10:24 UTC, Valeriya266 commented on style.css
>  body {
добавила

2024-10-19 10:29 UTC, Valeriya266 commented on style.css
>  body {
добавила overflow-x: hidden; в CSS для body

2024-10-19 12:20 UTC, Valeriya266 commented on style.css
> +div[class*=_container] {
исправила

2024-10-19 12:42 UTC, Valeriya266 commented on index.html
> +                <ul class="header__menu_menu-list">
исправила

2024-10-19 12:42 UTC, Valeriya266 commented on index.html
> +        <div class="content_container">
исправила

2024-10-19 13:55 UTC, Valeriya266 commented on index.html
> +            <div class="footer__phonenumber">+7 (812) 812-12-12</div>
сделала

2024-10-19 14:12 UTC, Allegathor commented on style.css
>  body {
> добавила overflow-x: hidden; в CSS для body

Это борьба с симптомами, а не причиной)
Надо разобраться, почему у тебя контент выходит за пределы видимой области

2024-10-19 14:13 UTC, Valeriya266 commented on style.css
> +p + p {
убрала

2024-10-19 14:13 UTC, Valeriya266 commented on index.html
> +            <div class="main-text__text">Рассмотрим 5 причин, по которым Седона круче, чем Гранд-Каньон!</div>
исправила

2024-10-20 11:21 UTC, Allegathor commented on index.html
> +            <div class="footer__phonenumber">+7 (812) 812-12-12</div>
Оформи так, чтобы при нажатии можно было позвонить (особенно актуально для смартфонов) 
Здесь подробности:
https://htmlacademy.ru/blog/html/mailto

2024-10-21 16:41 UTC, Allegathor requested changes

2024-10-21 16:41 UTC, Allegathor commented on index.html
> +                    <li class="header__menu-list-item_active"><a href="">Главная</a></li>
Модификатор не может использоваться в отрыве от основного класса. 
Если это блок, то используем так: \<div class="block block_mod"\>\</\>, если элемент, то \<div class="block__element block__element-mod"\>\</\>

2024-10-21 16:41 UTC, Allegathor commented on index.html
> +                    <li class="header__menu-list-item"><a href="">О Седоне</a></li>
Хорошей практикой считается использовать anchor tags для временных ссылок или пустых ссылок, т.е. href="#"

2024-10-21 16:41 UTC, Allegathor commented on index.html
> +        <section class="main-title">
Section не следует использовать без h1-h6 и какого-либо текста в принципе. В данном случае лучше заменить на div.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section

2024-10-21 16:41 UTC, Allegathor commented on index.html
> +        <section class="content content-font-color-1">
Имена цветов стоит более осмысленно называть
![image](https://github.com/user-attachments/assets/e8bb1165-9efa-4002-a090-6041c1ddbf10)
По палитре из стайлгайда можно следующим образом: black, white, primary-dark, primary-light, primary-gray, secondary-w-light, secondary-n-light, secondary-c-light (w, n, c - сокращения от warm, neutral и cold соответственно)  и т.д. Для статусов - status-error, status-warning, status-success

Ну и если мы говорим о цветах, то можно использовать модификаторы ключ-значение
![image](https://github.com/user-attachments/assets/b50ab2a8-c1d4-4fc4-9987-705bcfcbaf5b)
Т.е. в случае с цветом: content content_font-color_black

2024-10-21 16:41 UTC, Allegathor commented on index.html
> +        <section class="main-title">
И эту секцию (класс) лучше как-то иначе обозвать, а то дальше путаница начинается из-за названий. Пусть она будет, например, board или main-board

2024-10-21 16:41 UTC, Allegathor commented on index.html
> +        <section class="main-text">
Здесь тоже по названиям классов можно попроще и точнее: slogan, slogan__heading или slogan__title, slogan__note или slogan__description

2024-10-21 16:41 UTC, Allegathor commented on index.html
> +                <div class="find-hotel__text-text">Укажите предполагаемые даты поездки,<br>и мы покажем вам лучшие предложения гостиниц в Седоне</div>
find-hotel__text-text -- какое-то масло масленное)
Лучше или упростить и убрать элемент в виде div (не очень понял зачем нужен), либо можно оформить как контейнер: find-hotel__co > find-hotel__co-title find-hotel__co-text

2024-10-26 10:48 UTC, Valeriya266 commented on index.html
> +                    <li class="header__menu-list-item"><a href="">О Седоне</a></li>
добавила href="#"

2024-10-26 11:00 UTC, Valeriya266 commented on index.html
> +        <section class="main-title">
исправила на div секции без абзацев и заголовков, класс переименовала на "main-board"

2024-10-26 11:05 UTC, Valeriya266 commented on index.html
> +        <section class="main-text">
переименовала на "slogan-description"

2024-10-26 11:10 UTC, Valeriya266 commented on index.html
> +                <div class="find-hotel__text-text">Укажите предполагаемые даты поездки,<br>и мы покажем вам лучшие предложения гостиниц в Седоне</div>
сама не поняла зачем этот div здесь - убрала и исправила названия классов

2024-10-27 10:44 UTC, Valeriya266 commented on index.html
> +        <section class="content content-font-color-1">
исправила названия цветов фона и шрифта в css классах

2024-10-27 10:46 UTC, Valeriya266 commented on index.html
> +                    <li class="header__menu-list-item_active"><a href="">Главная</a></li>
исправила на <li class="header__menu-item-active">

2024-10-27 10:48 UTC, Valeriya266 commented on index.html
> +                    <li class="header__menu-list-item_active"><a href="">Главная</a></li>
исправила на <li class="header__menu-item-active"></>

2024-11-02 14:30 UTC, Valeriya266 commented on style.css
> +    line-height: 21px;
задала Line-hight в относительных единицах

2024-11-02 15:11 UTC, Valeriya266 commented on index.html
> +            <div class="footer__phonenumber">+7 (812) 812-12-12</div>
добавила href="tel:+78128121212"

2024-11-02 15:50 UTC, Valeriya266 commented on index.html
> +                <h1 class="find-hotel__text_title">Заинтересовались?</h1>
исправила

2024-11-04 17:00 UTC, Allegathor commented on index.html
> +                    <li class="header__menu-item-active"><a href="#">Главная</a></li>
Остался этот момент:
Модификатор не может использоваться в отрыве от основного класса.
Если это блок, то используем так: \<div class="block block_mod"\>\</\>, если элемент, то \<div class="block__element block__element-mod"\>\</\>

Суть в том, что у тебя есть основной класс (класс блока или элемента), где прописаны основные правила, он всегда применяется к элементу. И есть класс модификатора. Он используется для определённых ситуаций, например, для описания состояний. Класс модификатора НЕ МОЖЕТ использоваться без основного класса, как если бы мы пытались обратиться к св-ву ещё не созданного экземпляра класса в JS.

Должно быть так:
\<li class="header__menu header__menu_item-active\>

2024-11-04 17:00 UTC, Allegathor commented on index.html
> +            <div class="content__inf content_bg-color_secondary-c-light-02">
C цветами отлично! Только пропустила ещё сам элемент)
Т.е. блок или блок__элемент и модификатор, который применяем. 
В данном случае: content__inf_bg-color_secondary-c-light-02. 
Тогда тут может возникнуть проблема с тем, что цвет нужен во многих местах, а к каждому элементу писать это правило - так себе идея. Тут уже обычно отходят от классического и оригинального БЭМ и используют утилитарные классы. Например, если речь идёт о шрифте, можно ввести утилитарный класс-блок font (и уже к нему применять модификаторы). Если о фоне, то background или bg, ну и уже к этому блоку применять модификаторы. 
Есть вариант и попроще: прописывать цвет фона и шрифтов внутри для блоков и элементов, в css. Т.е. напрямую привязывать их к блокам и элементам. В данном случае проблем с этим не вижу - JS'ом влиять на цвета не надо, разных тем нет, поэтому можно обойтись малой кровью)

2024-11-04 17:00 UTC, Allegathor commented on index.html
> +            <div class="subscribe-form__text">
Тут я бы всё-таки назвал элемент не subscribe-form__text, а subscribe-from__container. 
И в целом название блока можно сократить до subscribe - будет меньше тавтологии и путаницы

2024-11-04 17:00 UTC, Allegathor commented on style.css
> +    line-height: 36px;
А тут не в относительных единициах line-height(

2024-11-13 17:51 UTC, Valeriya266 commented on index.html
> +            <div class="subscribe-form__text">
исправила

2024-11-13 17:55 UTC, Valeriya266 commented on style.css
> +    line-height: 36px;
исправила

2024-11-13 18:03 UTC, Valeriya266 commented on index.html
> +                    <li class="header__menu-item-active"><a href="#">Главная</a></li>
исправила

2024-11-13 18:18 UTC, Valeriya266 commented on index.html
> +            <div class="content__inf content_bg-color_secondary-c-light-02">
исправила этот момент

2024-12-10 17:22 UTC, merged